- name: Configure
        run: |
          ./mach configure

      - name: Download Artifacts
        run: |
          ./mach artifact install

      - name: Build
        run: |
          ./mach build

      - name: Package browser
        run: |
          ./mach package